Add files via upload
udacity/cn-translation-volunteer-training pull request #37
Opened 2017-06-02 14:58 UTC by Summer-Git

2017-06-06 12:47 UTC, caochenwei commented
@Jeff-Fang 可以审核一下吗？进阶的

2017-06-06 14:32 UTC, all2jeff requested changes
相当赞！还存在一些小问题，改一改就可以通过啦～

2017-06-06 14:32 UTC, all2jeff commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +速度会非常慢 效率也很低 有时甚至是无法打开打开文件的
重复

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +在电子表格应用中一个一个的手动处理
的->地

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +我们为你提供了test 函数
test前加空格

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +你将修改已给代码中的 parse filde 函数
函数名应该是`parse_file`

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +然后 你需要在 parse file 函数中返回这个列表
`parse_file`

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/fo4MJMkwhYU.srt
> +这个代码会调用 parse file 函数
`parse_file`

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/hmhlyOVAVOs.srt
> +我们要遍历这些字段并利用 enumerate() 方法
可以不用加括号。如果加的话至少在这个文件中保持一致，把所有方法都加上括号。

2017-06-06 14:32 UTC, Jeff-Fang commented on submissions/18_DANDa_subs/zh-cn/ra93hy88cok.srt
> +表格数据最常见的存储方法是 CSV 数据格式
原文“distribute”的含义就是发布／分发，并不是存储。

2017-06-06 14:38 UTC, all2jeff approved these changes

2017-06-09 02:33 UTC, caochenwei commented
@Summer-Git 其实可以直接在你的旧 Branch 修改，不需要重新提交哦

2017-06-09 02:33 UTC, closed without merging