Task 20 finished.
udacity/cn-translation-volunteer-training pull request #48
Opened 2017-06-07 13:07 UTC by zsq19900619

2017-06-09 14:37 UTC, all2jeff requested changes
相当赞！改动得非常细致！再把几个小细节改过来就可以通过辣～
记得要在同一个 branch 上进行修改哦～ 直接在 zsq19900619:task20 上做 commit 再 push 到 Github 上来，这份 pull request 就会自动更新。

2017-06-09 14:37 UTC, all2jeff commented on submissions/20_DANDa_subs/zh-cn/-rnzkOofIv0.srt
> +比如 Hard Days Night 的乘数是4
- _A Hard Day‘s Night_ 是披头士的一个专辑的名字。这种引用一个标点都不能动。
- 建议：比如《A Hard Day's Night》的乘数就是4

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/-rnzkOofIv0.srt
> +正如我们之前讨论过 JSON 对象可能会有嵌套对象
不必要的修改。在表达效果上差别不大时，应尽量选择更简洁的形式。

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/QCakJ5gxF5w.srt
> +英国广播公司BBC有一次录音节目还讨论了披头士的西班牙别名
BBC知名度很高，可以直接用，删掉英国广播公司。越简洁越好。

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/-rnzkOofIv0.srt
> +其他JSON 对象、单值或其他数组
空格问题。要么是`其他 JSON 对象`，要么用`其他 JSON对象`、要么`其他JSON对象`。您巧妙地避开了所有合理的写法。😂 
另外，如果严格按照[格式规范](https://github.com/udacity/cn-translation-volunteer-training/blob/master/documents/%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83.md), 应采用第一种空格用法。

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/QCakJ5gxF5w.srt
最好加上空格

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/QCakJ5gxF5w.srt
> +而One Direction 乐队的成立时间？2010年
空格

2017-06-09 14:37 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/tgni8KzxWzA.srt
> +并将从HTML 网页中抓取数据
空格

2017-06-10 01:17 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/QCakJ5gxF5w.srt
英文与汉字之间需要加入空格，而英文与中文标点符号之间无需加入空格。原因是，中文标点符号已经留好空白的距离了，而英文和英文标点符号并没有。这一点在您日常写作中也应该注意。在写英文时，用完英文标点符号之后都要空一格；而在写中文文章时，标点符号后面并不需要加入空格，就已经有合适的空白距离了。这涉及到一些字体排印的知识。感兴趣的话可以多了解一些。
在这里，正确的写法应该是 `那是与 John、Paul、George 和 Ringo 的一次采访`。是不是好看多了？

2017-06-10 01:24 UTC, Jeff-Fang commented on submissions/20_DANDa_subs/zh-cn/QCakJ5gxF5w.srt
> +那是与 John 、 Paul 、 George 和 Ringo 的一次采访
英文与汉字之间需要加入空格，而英文与中文标点符号之间无需加入空格。原因是，中文标点符号已经留好空白的距离了，而英文和英文标点符号并没有。这一点在您日常写作中也应该注意。在写英文时，用完英文标点符号之后都要空一格；而在写中文文章时，标点符号后面并不需要加入空格，就已经有合适的空白距离了。这涉及到一些字体排印的知识。感兴趣的话可以多了解一些。
在这里，正确的写法应该是 那是与 John、Paul、George 和 Ringo 的一次采访。是不是好看多了？

2017-06-10 01:40 UTC, Jeff-Fang commented
好的！ @caochenwei 可以merge了～

2017-06-10 06:57 UTC, merged