proofreading of task 9_DANDa_subs
udacity/cn-translation-volunteer-training pull request #70
Opened 2017-06-27 13:21 UTC by iwishwish

task 9_DANDa_subs is finished

2017-06-27 16:33 UTC, all2jeff requested changes
指出了一些问题，请改正。另外希望你可以再花一些精力，把一些你觉得别扭的翻译改改通顺。不用着急。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +臭虫(bug)很可能是最常见的一种甲虫
这里应该翻译成：对于甲壳虫最常用称呼就是 bug
因为这里按照视频的意思应该是对这种大众车型的称呼，不应完全理解成昆虫。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +但这里显示的昵称是 Bg 这只是一处打字错误
中文翻译可以不用与英文一一对应。在表达意思相差不多的情况下，应采用更简洁的译法。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +当数据产生的过程涉及人为操作时会出现差错，这经常发生
根据[格式规范](https://github.com/udacity/cn-translation-volunteer-training/blob/master/documents/%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83.md)，中文字幕中不应出现逗号、句号、分号和冒号。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +在继续之前我们再来看一个例子
中英文可以不用一一对应。在表达意思相差不多的时候应采用更简洁的译法。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/YM68DrqJw1I.srt
这个文件的第三句话有问题。 真的是「“廉价”经济学家」吗？有时英文也会有错误哦。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/zQj_waidR5w.srt
> +cast 函数 我们指定要更改的数据集 然后
前面解释了dcast函数中d的意思，这里应该是acast，a应该不是量词。

2017-06-27 16:33 UTC, Jeff-Fang commented on submissions/9_DANDa_subs/zh-cn/zQj_waidR5w.srt
> +因为 var.var 在新的数据框中保存关键测量项
应该是 value.var

2017-06-30 02:45 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +臭虫(bug)很可能是最常见的一种甲虫
已修改

2017-06-30 02:45 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +但这里显示的昵称是 Bg 这只是一处打字错误
已修改

2017-06-30 02:45 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +当数据产生的过程涉及人为操作时会出现差错，这经常发生
已修改

2017-06-30 02:45 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/8onBHqvvrig.srt
> +在继续之前我们再来看一个例子
已修改

2017-06-30 07:26 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/YM68DrqJw1I.srt
已修改

2017-06-30 07:44 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/zQj_waidR5w.srt
> +因为 var.var 在新的数据框中保存关键测量项
已修改

2017-06-30 07:45 UTC, iwishwish commented on submissions/9_DANDa_subs/zh-cn/zQj_waidR5w.srt
> +cast 函数 我们指定要更改的数据集 然后
已修改

2017-07-02 09:18 UTC, all2jeff approved these changes

2017-07-02 09:21 UTC, Jeff-Fang commented
@iwishwish 恭喜你通过了第一个任务！接下来可以认领第二个任务啦～
第二个任务是yaml文件校对，在校对之前请参考 README 中的说明信息，祝你顺利完成任务！

2017-07-02 09:23 UTC, Jeff-Fang commented
@caochenwei 可以merge啦～

2017-07-06 06:58 UTC, merged